### ISSUE TITLE
Question about using Activity in Method Call Handlers

### ISSUE THREAD

**Issue by doc-rj-celltrak** [pycampers/flutter-plugin-scaffold#4]
First of all, thanks for all the great Flutter contributions. Very helpful!

I want to follow this [example](https://github.com/flutter/flutter/issues/10769#issuecomment-309098062) so that I can use the host android Activity in my method call handlers.  Is there a way to do that with this plugin-scaffold plugin?

This plugin is used by flutter_cognito_plugin (which is also yours :) and I want to extend flutter_cognito_plugin by adding the [showSignIn() methods](https://aws-amplify.github.io/aws-sdk-android/docs/reference/com/amazonaws/mobile/client/AWSMobileClient.html#showSignIn-android.app.Activity-com.amazonaws.mobile.client.Callback-) to the Cognito class.  However, in order to call showSignIn() on AWSMobileClient, I need a reference to MainActivity.  I don't know if there is another way to do it.

I guess it's also appropriate to ask you if you have any plans to add the showSignIn() methods yourself?  My team needs to use the hosted UI only for a specific identity provider. Actually, I only need one version of the showSignIn() method, I don't need all four... Something like this in Java:

```
        HostedUIOptions hostedUIOptions = HostedUIOptions.builder()
                .identityProvider("MyProviderName")
                .build();
        SignInUIOptions signInUIOptions = SignInUIOptions.builder()
                .hostedUIOptions(hostedUIOptions)
                .build();
        AWSMobileClient.getInstance().showSignIn(this, signInUIOptions, new Callback<UserStateDetails>() { ... });
```

Thanks.

**Comment by ilikepi63** [comment]
Experiencing a similar issue. Need to know if I can handle this activity within my flutter app.

**Comment by devxpy** [comment]
Well, this is awkward -- I just saw this issue and have since, implemented [Hosted UI in the cognito plugin](https://github.com/scientifichackers/flutter_cognito_plugin/blob/9f69c3a04687faa197dfcdb680b7a0aa7264b4d3/android/src/main/kotlin/com/pycampers/flutter_cognito_plugin/Cognito.kt#L214).

FWIW, this issue is not really a limitation of plugin_scaffold -- all you need to do is just [pass around the `Activity`](https://github.com/scientifichackers/flutter_cognito_plugin/blob/9f69c3a04687faa197dfcdb680b7a0aa7264b4d3/android/src/main/kotlin/com/pycampers/flutter_cognito_plugin/FlutterCognitoPlugin.kt#L67) to an instance of the plugin class.
